### ISSUE TITLE
Typ parameter is required

### ISSUE THREAD

**Issue by andrei1489** [Jaguar-dart/session#1]
https://github.com/Jaguar-dart/session/blob/76ef847f086a16de405cef33cd4c1e84fe1735e8/jaguar_jwt/lib/src/jaguar_jwt.dart#L193

The plugin requires that the 'typ' header be set otherwise throws a JwtException.invalidToken. Since typ is optional, this breaks some setups.

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/session/commit/09d8d44007ac3682f903d1a3f9a6cbccc2f96637.

Released as `2.1.2`.

Let me know if it fixed the problem.

**Comment by andrei1489** [comment]
I confirm that it works. Thanks a lot for the fast help.
