### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by suragch** [Jaguar-dart/session#11]
Are you planning to migrate this library to null safety? I've appreciated using this package and one of my packages depends on it. If you are planning to migrate, I'll wait for that.

**Comment by tejainece** [comment]
I will fix it today.

**Comment by tejainece** [comment]
Null safety code is checked in. However, I will wait a couple of days before i publish to pub, since there are some breaking changes.

**Comment by suragch** [comment]
Thank you very much for your work on this. Breaking changes should be fine since I see you also bumped the major version number.

**Comment by debkanchan** [comment]
I think it's ok to publish new update

**Comment by tejainece** [comment]
Published version 3.0.0 to pub with null safety support.
