### ISSUE TITLE
SDK compatibility issue

### ISSUE THREAD

**Issue by sjmcdowall** [Jaguar-dart/session#2]
I am using the stable beta of flutter 0.58 so I can't use this package due to the demand of being at .60?

Running "flutter packages get" in mobile...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because MissionMode depends on jaguar_jwt >=2.1.1 which requires SDK version >=2.0.0-dev.60.0 <3.0.0, version solving failed.

Is there a reason to be dependent on dev.60 instead of dev.58 ??  If not can you make the compat to be >=2.0.0-dev.58.0 ???

**Comment by tejainece** [comment]
Fixing it.

**Comment by tejainece** [comment]
Fixed it. Also on pub.

**Comment by sjmcdowall** [comment]
I just tried this with 2.1.5 and I am getting the same error 
```
dependencies:
  shared_preferences: ^0.4.2
  scoped_model: ^0.2.0
  http: ^0.11.3+16
  rxdart: ^0.18.1
  jaguar_jwt: ^2.1.5

```
[mobile] flutter packages get
Running "flutter packages get" in mobile...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because MissionMode depends on jaguar_jwt >=2.1.1 which requires SDK version >=2.0.0-dev.60.0 <3.0.0, version solving failed.

-- also I see in the pub spec :    
environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

Doesn't that try to enforce a dev.65 sdk instead of a dev.58 as I thought it was going to do? 

I am fairly new to this .. am I doing something silly? 

Actually looking at the pub spec I'm not sure why the old >= 2.0.0 didn't work!? :(

**Comment by tejainece** [comment]
Jaguar supports flutter 0.5.8. Could you please upgrade Flutter?

**Comment by sjmcdowall** [comment]
I have multiple times but the current stable version of flutter is still beta 0.51 which has dart SDK 0.58?

Or is there a different upgrade option I should use ??  

```
 …/mms4/mobile  df4b6d7b  f/sjm/auth_login ● ?  flutter upgrade                       ✔  10032  06:50:09
Upgrading Flutter from /Users/sjm/Development/tools/flutter...
From https://github.com/flutter/flutter
   dc5a5c18a..3c624f8b2  master     -> origin/master
Already up to date.

Upgrading engine...
Already up-to-date.

Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

Running "flutter packages upgrade" in mobile...
The current Dart SDK version is 2.0.0-dev.58.0.flutter-f981f09760.

Because MissionMode depends on jaguar_jwt >=2.1.1 which requires SDK version >=2.0.0-dev.60.0 <3.0.0, version solving failed.
pub upgrade failed (1)
```

**Comment by tejainece** [comment]
> Doesn't that try to enforce a dev.65 sdk instead of a dev.58 as I thought it was going to do?

There are some syntax differences between dev.58 and dev.65. Some parts of Jaguar are written in dev.65/Dart2 syntax.

I recommend you to move to **dev channel** of Flutter. Because Flutter will move to Dart 2 in the future. Dart 1 (< Dart 2.0.0-dev.65) is not compatible with Dart 2 (>= Dart 2.0.0-dev.65). you will have to make some changes for it work with near future versions of Flutter.

**Comment by sjmcdowall** [comment]
Ok -- I'll give it a shot -- but I am sure Flutter already is on Dart 2 -- just a lower level SDK ..

**Comment by tejainece** [comment]
There are lot of differences between (< Dart 2.0.0-dev.65) and above.

**Comment by sjmcdowall** [comment]
Ok! with all the changes (upgrade a few other dependent packages) it now all works -- well -- at least the pub get works! :)  Thanks!

I think you should maybe add a dependency note for flutter users to make sure they are on the "dev" channel for this?   :)

**Comment by tejainece** [comment]
Glad that it works! Do let me know if you need assistance. 

You can also reach us at https://gitter.im/jaguar_dart/jaguar.
