### ISSUE TITLE
More flexible handling of custom claims (not just one payload called "pld")

### ISSUE THREAD

**Issue by hoylen** [Jaguar-dart/session#4]
**Requirement**

I want to use jaguar_jwt to implement JWTs that do not have a payload claim called `pld`, but instead has more than one claim with a different Claim Names. Also, one of those custom claims has a string value (i.e. the value is not a JSON object).

To implement the protocol I need to interoperate with, I need to generate and verify JWTs that has a body like:

```
{
  "sub": "some subject",
  "iss": "issuer.example.com",
  "http://example.com/custom": { "bar": "baz" },
  "abc": "xyz",
  "aud": "audience.example.com",
 ...
}
```

But jaguar_jwt only can only generate something like:

```
{
  "sub": "some subject",
  "iss": "issuer.example.com",
  "pld": { "k": "v" },
  "aud": ["audience.example.com"],
   ...
}
```

**Possible solutions**

I'm happy to write a pull request for it, but what do you prefer the API to look like?

For example, implement new issue/verify methods or extend the existing issue/verify methods in a non-breaking manner to support the extra functionality?

It is easy extending the existing issue/verify methods to include an optional payload Claim Name parameter (which defaults to "pld"). Though its value must always be a Map (JSON object). For example, the constructor could be:

    JwtClaimSet({...,
      String payloadName = 'pld',
      Map<String,dynamic> payload})

But supporting multiple extra claims is not as elegant if you want to keep backward compatibility, since the existing "payload" parameter is then a special case.

Here's one possible approach to support multiple custom claims. In this constructor, the _otherClaims_ is a map from Claim Name to value, and the values can be a Maps or scalar values (since not all custom claims are JSON objects; e.g. the "abc" in the above example).

    JwtClaimSet({...,
      Map<String,dynamic> otherClaims})
    
    // var a = new JwtClaimSet(otherClaims: { 'pld': { 'k': 'v' } };
    // var b = new JwtClaimSet(otherClaims: { 'abc': 'xyz',
                                              'http://example.com/custom': { 'bar': 'baz' } };

But to maintain backward compatibility, the existing _payload_ parameter still needs to appear as a special case (even though _otherClaims_ can be used for it).

    JwtClaimSet({...,
      String payloadName = 'pld',
      Map<String,dynamic> payload,
      Map<String,dynamic> otherClaims})

**Comment by tejainece** [comment]
@hoylen 

What do you think about this idea:

A field in `JwtClaim` called `bool inlinePayload = false;`. If this is set to true, the payload map is inlined (merged with the actual claimset) instead. If it is false (the default so that it is backward compatible), claimset['pld'] is used. We can also have a field/parameter to configure the key used for non-inlinined payload.

Another question would be, should we filter out standard claims from payload map when it is inlined?

**Comment by tejainece** [comment]
I think the best approach is to break compatibility and use `Map<String,dynamic> otherClaims` and remove old payload.

**Comment by hoylen** [comment]
The _inlinePayload_ sounds good to me.

If a standard claim (RFC 7519 calls them "Registered Claim Names") is found, I'm tempted to throw an [ArgumentError](https://api.dartlang.org/stable/1.24.3/dart-core/ArgumentError-class.html) since the programmer probably shouldn't be doing that. If it is allowed, then we have created more work to deal with lots of error situations (e.g. it is the wrong type (String for an _expiry_ claim) or what if it is provided in the _otherClaims_ as well as an explicit parameter).

I'm happy to break compatibility, if you are happy to advance the version number for it.

I wonder if that is a way to implement the _inlinePayload_ parameter, but signal the use of _payload_ as deprecated: so people's old code still works, but they are warned about the coming breaking change.

**Comment by tejainece** [comment]
We can go with `Map<String,dynamic> otherClaims`. `payload` could just be a getter operating on `otherClaim`. This way, we don't break compatibility.

```dart
Map<String, dynamic> get payload = otherClaims['pld'];
```

In constructor, if `payload` is not null, we can set it in `otherClaims`.

What do you think?

**Comment by hoylen** [comment]
Making _payload_ a getter on _otherClaim_ is a great idea. Dart was designed for that!

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/session/pull/6
